#ifndef SCREWDRIVER_CONTEXT_HPP
#define SCREWDRIVER_CONTEXT_HPP

#if defined(_MSC_VER)
# pragma once
#endif

#include <boost/config.hpp>

#if defined(SCREWDRIVER_CONTEXT_LINK_DYNAMIC)
# if defined(SCREWDRIVER_CONTEXT_COMPILATION)
#   define SCREWDRIVER_CONTEXT_API BOOST_SYMBOL_EXPORT
# else
#   define SCREWDRIVER_CONTEXT_API BOOST_SYMBOL_IMPORT
# endif
#else
# define SCREWDRIVER_CONTEXT_API
#endif
#endif // SCREWDRIVER_CONTEXT_HPP

