#ifndef SCREWDRIVER_INFRASTRUCTURE_HPP
#define SCREWDRIVER_INFRASTRUCTURE_HPP

#if defined(_MSC_VER)
# pragma once
#endif

#include <boost/config.hpp>

#if defined(SCREWDRIVER_INFRASTRUCTURE_LINK_DYNAMIC)
# if defined(SCREWDRIVER_INFRASTRUCTURE_COMPILATION)
#   define SCREWDRIVER_INFRASTRUCTURE_API BOOST_SYMBOL_EXPORT
# else
#   define SCREWDRIVER_INFRASTRUCTURE_API BOOST_SYMBOL_IMPORT
# endif
#else
# define SCREWDRIVER_INFRASTRUCTURE_API
#endif
#endif // SCREWDRIVER_INFRASTRUCTURE_HPP

